// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {nuvem} from '../models';
import {revisao} from '../models';
import {dicionario} from '../models';
import {tela} from '../models';
import {config} from '../models';
import {progresso} from '../models';
import {jornada} from '../models';
import {notasversao} from '../models';

export function AbrirPastaDados():Promise<void>;

export function AddVocab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AdicionarHanziFoco(arg1:string):Promise<void>;

export function AtualizarAtalhosGlobais():Promise<Record<string, string>>;

export function AvaliarTipoHanzi(arg1:string):Promise<string>;

export function BaixarModelo(arg1:string):Promise<void>;

export function BaixarMotor(arg1:string):Promise<void>;

export function BaixarMotorStt(arg1:string):Promise<void>;

export function BaixarMotorTts(arg1:string):Promise<void>;

export function BuscarCaracteresCompostosPor(arg1:string):Promise<Array<string>>;

export function BuscarNoDicionarioGeral(arg1:string):Promise<Array<main.FlashcardCard>>;

export function BuscarPorPinyin(arg1:string):Promise<Array<string>>;

export function CancelarEscutaStt():Promise<void>;

export function CaptureAndOCR():Promise<Array<main.FlashcardCard>>;

export function CaractereCompleto(arg1:string):Promise<string>;

export function ConectarNuvem():Promise<nuvem.Info>;

export function ConverterTexto(arg1:string,arg2:string):Promise<string>;

export function DecomporTextoRevisao(arg1:string):Promise<Array<revisao.PalavraRevisao>>;

export function DecomposeCharacter(arg1:string):Promise<dicionario.DecomposicaoHanzi>;

export function DescartarFraseIA(arg1:string):Promise<boolean>;

export function DescartarPerguntaCompreensaoIA(arg1:string):Promise<boolean>;

export function DesconectarNuvem():Promise<nuvem.Info>;

export function DespertarMotorStt():Promise<void>;

export function DespertarMotorTts():Promise<void>;

export function ExcluirTudo():Promise<void>;

export function FalarPinyin(arg1:string,arg2:string):Promise<string>;

export function FalarPinyinRevisao(arg1:string,arg2:string):Promise<string>;

export function GerarFrasesComIA(arg1:number):Promise<number>;

export function GerarPerguntasCompreensaoComIA(arg1:number):Promise<number>;

export function GetCaptureResolution():Promise<tela.Resolucao>;

export function GetConfig():Promise<config.Config>;

export function GetCotaGemini():Promise<main.InfoCotaGemini>;

export function GetCotaTraducao():Promise<main.InfoCotaTraducao>;

export function GetInfoNuvem():Promise<nuvem.Info>;

export function GetLastCards():Promise<Array<main.FlashcardCard>>;

export function GetLastScreenshot():Promise<string>;

export function GetMonitores():Promise<Array<tela.Monitor>>;

export function GetSessionImage(arg1:number):Promise<string>;

export function GetStorageInfo():Promise<main.StorageInfo>;

export function GetSystemHardware():Promise<main.SystemHardware>;

export function GetVocab():Promise<Array<progresso.Vocab>>;

export function HideHoverPopup():Promise<void>;

export function IniciarAtualizacao(arg1:string):Promise<void>;

export function IniciarEscutaStt():Promise<void>;

export function InvalidarSintesesTts():Promise<void>;

export function LimparArmazenamento(arg1:string):Promise<void>;

export function ListarModelos():Promise<Array<main.ModeloOcrInfo>>;

export function ListarMotores():Promise<Array<main.MotorOcrInfo>>;

export function ListarMotoresStt():Promise<Array<main.MotorSttInfo>>;

export function ListarMotoresTts():Promise<Array<main.MotorTtsInfo>>;

export function LookupWord(arg1:string):Promise<Array<dicionario.EntradaDicionario>>;

export function MarcarNotasVersaoVistas(arg1:Array<string>):Promise<void>;

export function MarcarVistoSilencioso(arg1:string):Promise<void>;

export function ObterArvoreJornada():Promise<jornada.Arvore>;

export function ObterClipesCacheTts(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function ObterDadosEscritaHanzi(arg1:string):Promise<string>;

export function ObterEstadoAtualizacao():Promise<main.EstadoAtualizacao>;

export function ObterEstatisticasPalavra(arg1:string):Promise<Record<string, number>>;

export function ObterFocoRevisao():Promise<Array<revisao.ItemFocoRevisao>>;

export function ObterFrasesIA():Promise<Array<progresso.FraseUsuario>>;

export function ObterInformacaoExpansao(arg1:string):Promise<main.InformacaoExpansao>;

export function ObterNotasVersao():Promise<Array<notasversao.Nota>>;

export function ObterNotasVersaoNaoVistas():Promise<Array<notasversao.Nota>>;

export function ObterPerguntasCompreensaoIA():Promise<Array<progresso.PerguntaCompreensaoUsuario>>;

export function ObterPrimeiraQuestaoJornada(arg1:string,arg2:number):Promise<revisao.QuestaoRevisao>;

export function ObterPrimeiraQuestaoRevisao(arg1:string):Promise<revisao.QuestaoRevisao>;

export function ObterProgressoJornada():Promise<Record<string, number>>;

export function ObterProgressoRevisaoPalavras(arg1:Array<string>):Promise<revisao.ProgressoRevisaoPalavras>;

export function ObterQuestoesJornada(arg1:string,arg2:number):Promise<Array<revisao.QuestaoRevisao>>;

export function ObterQuestoesJornadaComPrimeira(arg1:string,arg2:number,arg3:revisao.QuestaoRevisao):Promise<Array<revisao.QuestaoRevisao>>;

export function ObterQuestoesRevisao(arg1:string,arg2:number):Promise<Array<revisao.QuestaoRevisao>>;

export function ObterQuestoesRevisaoComPrimeira(arg1:string,arg2:number,arg3:revisao.QuestaoRevisao):Promise<Array<revisao.QuestaoRevisao>>;

export function ObterRecomendacoesBaralho(arg1:boolean):Promise<Array<main.RecomendacaoBaralho>>;

export function ObterSugestoesAprendidoLote(arg1:Array<string>,arg2:Array<string>):Promise<Array<progresso.Vocab>>;

export function ObterSugestoesEstudoOcr():Promise<Array<progresso.Vocab>>;

export function ObterTotalHanzisDicionario():Promise<number>;

export function OcultarSugestoesEstudoOcr(arg1:Array<string>):Promise<void>;

export function PararEscutaStt():Promise<string>;

export function PararPreCacheTts():Promise<void>;

export function PreCarregarCacheTts(arg1:string):Promise<void>;

export function RegistrarRespostaFrase(arg1:Array<revisao.PalavraRevisao>,arg2:Array<string>,arg3:boolean):Promise<void>;

export function RegistrarRespostaRevisao(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function RegistrarRevisaoJornadaConcluida(arg1:string,arg2:number):Promise<void>;

export function ReiniciarAplicativo():Promise<void>;

export function RemoveVocab(arg1:string):Promise<void>;

export function RemoverHanziFoco(arg1:string):Promise<void>;

export function RemoverModelo(arg1:string):Promise<void>;

export function RemoverMotor(arg1:string):Promise<void>;

export function RemoverMotorStt(arg1:string):Promise<void>;

export function RemoverMotorTts(arg1:string):Promise<void>;

export function ResolverConflitoNuvem(arg1:string):Promise<nuvem.Info>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SegmentarTexto(arg1:string):Promise<Array<string>>;

export function ShowEstudoHighlights(arg1:Array<any>):Promise<void>;

export function ShowEstudoParcialHighlights(arg1:Array<any>):Promise<void>;

export function ShowHighlight(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ShowHoverPopup(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function SincronizarNuvem():Promise<nuvem.Info>;

export function StartBackgroundLoop():Promise<void>;

export function TrocarMotor(arg1:string):Promise<void>;

export function VerificarAtualizacao(arg1:string):Promise<main.ResultadoVerificacaoAtualizacao>;

export function VirarCartaBaralho(arg1:string,arg2:boolean):Promise<void>;
