// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {nuvem} from '../models';
import {dicionario} from '../models';
import {config} from '../models';
import {progresso} from '../models';

export function AbrirPastaDados():Promise<void>;

export function AddVocab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AvaliarTipoHanzi(arg1:string):Promise<string>;

export function BaixarModelo(arg1:string):Promise<void>;

export function BaixarMotor(arg1:string):Promise<void>;

export function BaixarMotorStt(arg1:string):Promise<void>;

export function BaixarMotorTts(arg1:string):Promise<void>;

export function BuscarCaracteresCompostosPor(arg1:string):Promise<Array<string>>;

export function BuscarNoDicionarioGeral(arg1:string):Promise<Array<main.FlashcardCard>>;

export function BuscarPorPinyin(arg1:string):Promise<Array<string>>;

export function CancelarEscutaStt():Promise<void>;

export function CaptureAndOCR():Promise<Array<main.FlashcardCard>>;

export function CaractereCompleto(arg1:string):Promise<string>;

export function ConectarNuvem():Promise<nuvem.Info>;

export function DecomposeCharacter(arg1:string):Promise<dicionario.DecomposicaoHanzi>;

export function DesconectarNuvem():Promise<nuvem.Info>;

export function DespertarMotorStt():Promise<void>;

export function DespertarMotorTts():Promise<void>;

export function ExcluirTudo():Promise<void>;

export function FalarPinyin(arg1:string,arg2:string):Promise<string>;

export function GetCaptureResolution():Promise<main.Resolucao>;

export function GetConfig():Promise<config.Config>;

export function GetCotaGemini():Promise<main.InfoCotaGemini>;

export function GetCotaTraducao():Promise<main.InfoCotaTraducao>;

export function GetInfoNuvem():Promise<nuvem.Info>;

export function GetLastCards():Promise<Array<main.FlashcardCard>>;

export function GetLastScreenshot():Promise<string>;

export function GetMonitores():Promise<Array<main.Monitor>>;

export function GetSessionImage(arg1:number):Promise<string>;

export function GetStorageInfo():Promise<main.StorageInfo>;

export function GetSystemHardware():Promise<main.SystemHardware>;

export function GetVocab():Promise<Array<progresso.Vocab>>;

export function HideHoverPopup():Promise<void>;

export function IniciarEscutaStt():Promise<void>;

export function LimparArmazenamento(arg1:string):Promise<void>;

export function ListarModelos():Promise<Array<main.ModeloOcrInfo>>;

export function ListarMotores():Promise<Array<main.MotorOcrInfo>>;

export function ListarMotoresStt():Promise<Array<main.MotorSttInfo>>;

export function ListarMotoresTts():Promise<Array<main.MotorTtsInfo>>;

export function LookupWord(arg1:string):Promise<Array<dicionario.EntradaDicionario>>;

export function MarcarVistoSilencioso(arg1:string):Promise<void>;

export function ObterDadosEscritaHanzi(arg1:string):Promise<string>;

export function ObterQuestoesRevisao(arg1:string,arg2:number):Promise<Array<main.QuestaoRevisao>>;

export function ObterTotalHanzisDicionario():Promise<number>;

export function PararEscutaStt():Promise<string>;

export function PararPreCacheTts():Promise<void>;

export function PreCarregarCacheTts(arg1:string):Promise<void>;

export function RemoveVocab(arg1:string):Promise<void>;

export function RemoverModelo(arg1:string):Promise<void>;

export function RemoverMotor(arg1:string):Promise<void>;

export function RemoverMotorStt(arg1:string):Promise<void>;

export function RemoverMotorTts(arg1:string):Promise<void>;

export function ResolverConflitoNuvem(arg1:string):Promise<nuvem.Info>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ShowEstudoHighlights(arg1:Array<any>):Promise<void>;

export function ShowEstudoParcialHighlights(arg1:Array<any>):Promise<void>;

export function ShowHighlight(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ShowHoverPopup(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function SincronizarNuvem():Promise<nuvem.Info>;

export function StartBackgroundLoop():Promise<void>;

export function TrocarMotor(arg1:string):Promise<void>;
