// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirPastaDados() {
  return window['go']['main']['App']['AbrirPastaDados']();
}

export function AddVocab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddVocab'](arg1, arg2, arg3, arg4);
}

export function AvaliarTipoHanzi(arg1) {
  return window['go']['main']['App']['AvaliarTipoHanzi'](arg1);
}

export function BaixarModelo(arg1) {
  return window['go']['main']['App']['BaixarModelo'](arg1);
}

export function BaixarMotor(arg1) {
  return window['go']['main']['App']['BaixarMotor'](arg1);
}

export function BaixarMotorStt(arg1) {
  return window['go']['main']['App']['BaixarMotorStt'](arg1);
}

export function BaixarMotorTts(arg1) {
  return window['go']['main']['App']['BaixarMotorTts'](arg1);
}

export function BuscarCaracteresCompostosPor(arg1) {
  return window['go']['main']['App']['BuscarCaracteresCompostosPor'](arg1);
}

export function BuscarNoDicionarioGeral(arg1) {
  return window['go']['main']['App']['BuscarNoDicionarioGeral'](arg1);
}

export function BuscarPorPinyin(arg1) {
  return window['go']['main']['App']['BuscarPorPinyin'](arg1);
}

export function CancelarEscutaStt() {
  return window['go']['main']['App']['CancelarEscutaStt']();
}

export function CaptureAndOCR() {
  return window['go']['main']['App']['CaptureAndOCR']();
}

export function CaractereCompleto(arg1) {
  return window['go']['main']['App']['CaractereCompleto'](arg1);
}

export function ConectarNuvem() {
  return window['go']['main']['App']['ConectarNuvem']();
}

export function DecomposeCharacter(arg1) {
  return window['go']['main']['App']['DecomposeCharacter'](arg1);
}

export function DecomporTextoRevisao(arg1) {
  return window['go']['main']['App']['DecomporTextoRevisao'](arg1);
}

export function DesconectarNuvem() {
  return window['go']['main']['App']['DesconectarNuvem']();
}

export function DespertarMotorStt() {
  return window['go']['main']['App']['DespertarMotorStt']();
}

export function DespertarMotorTts() {
  return window['go']['main']['App']['DespertarMotorTts']();
}

export function ExcluirTudo() {
  return window['go']['main']['App']['ExcluirTudo']();
}

export function FalarPinyin(arg1, arg2) {
  return window['go']['main']['App']['FalarPinyin'](arg1, arg2);
}

export function GetCaptureResolution() {
  return window['go']['main']['App']['GetCaptureResolution']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCotaGemini() {
  return window['go']['main']['App']['GetCotaGemini']();
}

export function GetCotaTraducao() {
  return window['go']['main']['App']['GetCotaTraducao']();
}

export function GetInfoNuvem() {
  return window['go']['main']['App']['GetInfoNuvem']();
}

export function GetLastCards() {
  return window['go']['main']['App']['GetLastCards']();
}

export function GetLastScreenshot() {
  return window['go']['main']['App']['GetLastScreenshot']();
}

export function GetMonitores() {
  return window['go']['main']['App']['GetMonitores']();
}

export function GetSessionImage(arg1) {
  return window['go']['main']['App']['GetSessionImage'](arg1);
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetSystemHardware() {
  return window['go']['main']['App']['GetSystemHardware']();
}

export function GetVocab() {
  return window['go']['main']['App']['GetVocab']();
}

export function HideHoverPopup() {
  return window['go']['main']['App']['HideHoverPopup']();
}

export function IniciarEscutaStt() {
  return window['go']['main']['App']['IniciarEscutaStt']();
}

export function LimparArmazenamento(arg1) {
  return window['go']['main']['App']['LimparArmazenamento'](arg1);
}

export function ListarModelos() {
  return window['go']['main']['App']['ListarModelos']();
}

export function ListarMotores() {
  return window['go']['main']['App']['ListarMotores']();
}

export function ListarMotoresStt() {
  return window['go']['main']['App']['ListarMotoresStt']();
}

export function ListarMotoresTts() {
  return window['go']['main']['App']['ListarMotoresTts']();
}

export function LookupWord(arg1) {
  return window['go']['main']['App']['LookupWord'](arg1);
}

export function MarcarVistoSilencioso(arg1) {
  return window['go']['main']['App']['MarcarVistoSilencioso'](arg1);
}

export function ObterDadosEscritaHanzi(arg1) {
  return window['go']['main']['App']['ObterDadosEscritaHanzi'](arg1);
}

export function ObterQuestoesRevisao(arg1, arg2) {
  return window['go']['main']['App']['ObterQuestoesRevisao'](arg1, arg2);
}

export function ObterTotalHanzisDicionario() {
  return window['go']['main']['App']['ObterTotalHanzisDicionario']();
}

export function PararEscutaStt() {
  return window['go']['main']['App']['PararEscutaStt']();
}

export function PararPreCacheTts() {
  return window['go']['main']['App']['PararPreCacheTts']();
}

export function PreCarregarCacheTts(arg1) {
  return window['go']['main']['App']['PreCarregarCacheTts'](arg1);
}

export function RemoveVocab(arg1) {
  return window['go']['main']['App']['RemoveVocab'](arg1);
}

export function RemoverModelo(arg1) {
  return window['go']['main']['App']['RemoverModelo'](arg1);
}

export function RemoverMotor(arg1) {
  return window['go']['main']['App']['RemoverMotor'](arg1);
}

export function RemoverMotorStt(arg1) {
  return window['go']['main']['App']['RemoverMotorStt'](arg1);
}

export function RemoverMotorTts(arg1) {
  return window['go']['main']['App']['RemoverMotorTts'](arg1);
}

export function ResolverConflitoNuvem(arg1) {
  return window['go']['main']['App']['ResolverConflitoNuvem'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowEstudoHighlights(arg1) {
  return window['go']['main']['App']['ShowEstudoHighlights'](arg1);
}

export function ShowEstudoParcialHighlights(arg1) {
  return window['go']['main']['App']['ShowEstudoParcialHighlights'](arg1);
}

export function ShowHighlight(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ShowHighlight'](arg1, arg2, arg3, arg4);
}

export function ShowHoverPopup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ShowHoverPopup'](arg1, arg2, arg3, arg4, arg5);
}

export function SincronizarNuvem() {
  return window['go']['main']['App']['SincronizarNuvem']();
}

export function StartBackgroundLoop() {
  return window['go']['main']['App']['StartBackgroundLoop']();
}

export function TrocarMotor(arg1) {
  return window['go']['main']['App']['TrocarMotor'](arg1);
}

export function ObterEstatisticasPalavra(arg1) {
  return window['go']['main']['App']['ObterEstatisticasPalavra'](arg1);
}

export function RegistrarRespostaRevisao(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegistrarRespostaRevisao'](arg1, arg2, arg3, arg4, arg5);
}

export function ObterSugestoesAprendidoLote(arg1) {
  return window['go']['main']['App']['ObterSugestoesAprendidoLote'](arg1);
}
