// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirPastaDados() {
  return window['go']['main']['App']['AbrirPastaDados']();
}

export function AddVocab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddVocab'](arg1, arg2, arg3, arg4);
}

export function AdicionarHanziFoco(arg1) {
  return window['go']['main']['App']['AdicionarHanziFoco'](arg1);
}

export function AtualizarAtalhosGlobais() {
  return window['go']['main']['App']['AtualizarAtalhosGlobais']();
}

export function AvaliarTipoHanzi(arg1) {
  return window['go']['main']['App']['AvaliarTipoHanzi'](arg1);
}

export function BaixarModelo(arg1) {
  return window['go']['main']['App']['BaixarModelo'](arg1);
}

export function BaixarMotor(arg1) {
  return window['go']['main']['App']['BaixarMotor'](arg1);
}

export function BaixarMotorStt(arg1) {
  return window['go']['main']['App']['BaixarMotorStt'](arg1);
}

export function BaixarMotorTts(arg1) {
  return window['go']['main']['App']['BaixarMotorTts'](arg1);
}

export function BuscarCaracteresCompostosPor(arg1) {
  return window['go']['main']['App']['BuscarCaracteresCompostosPor'](arg1);
}

export function BuscarNoDicionarioGeral(arg1) {
  return window['go']['main']['App']['BuscarNoDicionarioGeral'](arg1);
}

export function BuscarPorPinyin(arg1) {
  return window['go']['main']['App']['BuscarPorPinyin'](arg1);
}

export function CancelarEscutaStt() {
  return window['go']['main']['App']['CancelarEscutaStt']();
}

export function CaptureAndOCR() {
  return window['go']['main']['App']['CaptureAndOCR']();
}

export function CaractereCompleto(arg1) {
  return window['go']['main']['App']['CaractereCompleto'](arg1);
}

export function ConectarNuvem() {
  return window['go']['main']['App']['ConectarNuvem']();
}

export function ConverterTexto(arg1, arg2) {
  return window['go']['main']['App']['ConverterTexto'](arg1, arg2);
}

export function DecomporTextoRevisao(arg1) {
  return window['go']['main']['App']['DecomporTextoRevisao'](arg1);
}

export function DecomposeCharacter(arg1) {
  return window['go']['main']['App']['DecomposeCharacter'](arg1);
}

export function DescartarFraseIA(arg1) {
  return window['go']['main']['App']['DescartarFraseIA'](arg1);
}

export function DescartarPerguntaCompreensaoIA(arg1) {
  return window['go']['main']['App']['DescartarPerguntaCompreensaoIA'](arg1);
}

export function DesconectarNuvem() {
  return window['go']['main']['App']['DesconectarNuvem']();
}

export function DespertarMotorStt() {
  return window['go']['main']['App']['DespertarMotorStt']();
}

export function DespertarMotorTts() {
  return window['go']['main']['App']['DespertarMotorTts']();
}

export function ExcluirTudo() {
  return window['go']['main']['App']['ExcluirTudo']();
}

export function FalarPinyin(arg1, arg2) {
  return window['go']['main']['App']['FalarPinyin'](arg1, arg2);
}

export function FalarPinyinRevisao(arg1, arg2) {
  return window['go']['main']['App']['FalarPinyinRevisao'](arg1, arg2);
}

export function GerarFrasesComIA(arg1) {
  return window['go']['main']['App']['GerarFrasesComIA'](arg1);
}

export function GerarPerguntasCompreensaoComIA(arg1) {
  return window['go']['main']['App']['GerarPerguntasCompreensaoComIA'](arg1);
}

export function GetCaptureResolution() {
  return window['go']['main']['App']['GetCaptureResolution']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCotaGemini() {
  return window['go']['main']['App']['GetCotaGemini']();
}

export function GetCotaTraducao() {
  return window['go']['main']['App']['GetCotaTraducao']();
}

export function GetInfoNuvem() {
  return window['go']['main']['App']['GetInfoNuvem']();
}

export function GetLastCards() {
  return window['go']['main']['App']['GetLastCards']();
}

export function GetLastScreenshot() {
  return window['go']['main']['App']['GetLastScreenshot']();
}

export function GetMonitores() {
  return window['go']['main']['App']['GetMonitores']();
}

export function GetSessionImage(arg1) {
  return window['go']['main']['App']['GetSessionImage'](arg1);
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetSystemHardware() {
  return window['go']['main']['App']['GetSystemHardware']();
}

export function GetVocab() {
  return window['go']['main']['App']['GetVocab']();
}

export function HideHoverPopup() {
  return window['go']['main']['App']['HideHoverPopup']();
}

export function IniciarAtualizacao(arg1) {
  return window['go']['main']['App']['IniciarAtualizacao'](arg1);
}

export function IniciarEscutaStt() {
  return window['go']['main']['App']['IniciarEscutaStt']();
}

export function InvalidarSintesesTts() {
  return window['go']['main']['App']['InvalidarSintesesTts']();
}

export function LimparArmazenamento(arg1) {
  return window['go']['main']['App']['LimparArmazenamento'](arg1);
}

export function ListarModelos() {
  return window['go']['main']['App']['ListarModelos']();
}

export function ListarMotores() {
  return window['go']['main']['App']['ListarMotores']();
}

export function ListarMotoresStt() {
  return window['go']['main']['App']['ListarMotoresStt']();
}

export function ListarMotoresTts() {
  return window['go']['main']['App']['ListarMotoresTts']();
}

export function LookupWord(arg1) {
  return window['go']['main']['App']['LookupWord'](arg1);
}

export function MarcarNotasVersaoVistas(arg1) {
  return window['go']['main']['App']['MarcarNotasVersaoVistas'](arg1);
}

export function MarcarVistoSilencioso(arg1) {
  return window['go']['main']['App']['MarcarVistoSilencioso'](arg1);
}

export function ObterArvoreJornada() {
  return window['go']['main']['App']['ObterArvoreJornada']();
}

export function ObterClipesCacheTts(arg1, arg2) {
  return window['go']['main']['App']['ObterClipesCacheTts'](arg1, arg2);
}

export function ObterDadosEscritaHanzi(arg1) {
  return window['go']['main']['App']['ObterDadosEscritaHanzi'](arg1);
}

export function ObterEstadoAtualizacao() {
  return window['go']['main']['App']['ObterEstadoAtualizacao']();
}

export function ObterEstatisticasPalavra(arg1) {
  return window['go']['main']['App']['ObterEstatisticasPalavra'](arg1);
}

export function ObterFocoRevisao() {
  return window['go']['main']['App']['ObterFocoRevisao']();
}

export function ObterFrasesIA() {
  return window['go']['main']['App']['ObterFrasesIA']();
}

export function ObterInformacaoExpansao(arg1) {
  return window['go']['main']['App']['ObterInformacaoExpansao'](arg1);
}

export function ObterNotasVersao() {
  return window['go']['main']['App']['ObterNotasVersao']();
}

export function ObterNotasVersaoNaoVistas() {
  return window['go']['main']['App']['ObterNotasVersaoNaoVistas']();
}

export function ObterPerguntasCompreensaoIA() {
  return window['go']['main']['App']['ObterPerguntasCompreensaoIA']();
}

export function ObterPrimeiraQuestaoJornada(arg1, arg2) {
  return window['go']['main']['App']['ObterPrimeiraQuestaoJornada'](arg1, arg2);
}

export function ObterPrimeiraQuestaoRevisao(arg1) {
  return window['go']['main']['App']['ObterPrimeiraQuestaoRevisao'](arg1);
}

export function ObterProgressoJornada() {
  return window['go']['main']['App']['ObterProgressoJornada']();
}

export function ObterProgressoRevisaoPalavras(arg1) {
  return window['go']['main']['App']['ObterProgressoRevisaoPalavras'](arg1);
}

export function ObterQuestoesJornada(arg1, arg2) {
  return window['go']['main']['App']['ObterQuestoesJornada'](arg1, arg2);
}

export function ObterQuestoesJornadaComPrimeira(arg1, arg2, arg3) {
  return window['go']['main']['App']['ObterQuestoesJornadaComPrimeira'](arg1, arg2, arg3);
}

export function ObterQuestoesRevisao(arg1, arg2) {
  return window['go']['main']['App']['ObterQuestoesRevisao'](arg1, arg2);
}

export function ObterQuestoesRevisaoComPrimeira(arg1, arg2, arg3) {
  return window['go']['main']['App']['ObterQuestoesRevisaoComPrimeira'](arg1, arg2, arg3);
}

export function ObterRecomendacoesBaralho(arg1) {
  return window['go']['main']['App']['ObterRecomendacoesBaralho'](arg1);
}

export function ObterSugestoesAprendidoLote(arg1, arg2) {
  return window['go']['main']['App']['ObterSugestoesAprendidoLote'](arg1, arg2);
}

export function ObterSugestoesEstudoOcr() {
  return window['go']['main']['App']['ObterSugestoesEstudoOcr']();
}

export function ObterTotalHanzisDicionario() {
  return window['go']['main']['App']['ObterTotalHanzisDicionario']();
}

export function OcultarSugestoesEstudoOcr(arg1) {
  return window['go']['main']['App']['OcultarSugestoesEstudoOcr'](arg1);
}

export function PararEscutaStt() {
  return window['go']['main']['App']['PararEscutaStt']();
}

export function PararPreCacheTts() {
  return window['go']['main']['App']['PararPreCacheTts']();
}

export function PreCarregarCacheTts(arg1) {
  return window['go']['main']['App']['PreCarregarCacheTts'](arg1);
}

export function RegistrarRespostaFrase(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegistrarRespostaFrase'](arg1, arg2, arg3);
}

export function RegistrarRespostaRevisao(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegistrarRespostaRevisao'](arg1, arg2, arg3, arg4, arg5);
}

export function RegistrarRevisaoJornadaConcluida(arg1, arg2) {
  return window['go']['main']['App']['RegistrarRevisaoJornadaConcluida'](arg1, arg2);
}

export function ReiniciarAplicativo() {
  return window['go']['main']['App']['ReiniciarAplicativo']();
}

export function RemoveVocab(arg1) {
  return window['go']['main']['App']['RemoveVocab'](arg1);
}

export function RemoverHanziFoco(arg1) {
  return window['go']['main']['App']['RemoverHanziFoco'](arg1);
}

export function RemoverModelo(arg1) {
  return window['go']['main']['App']['RemoverModelo'](arg1);
}

export function RemoverMotor(arg1) {
  return window['go']['main']['App']['RemoverMotor'](arg1);
}

export function RemoverMotorStt(arg1) {
  return window['go']['main']['App']['RemoverMotorStt'](arg1);
}

export function RemoverMotorTts(arg1) {
  return window['go']['main']['App']['RemoverMotorTts'](arg1);
}

export function ResolverConflitoNuvem(arg1) {
  return window['go']['main']['App']['ResolverConflitoNuvem'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SegmentarTexto(arg1) {
  return window['go']['main']['App']['SegmentarTexto'](arg1);
}

export function ShowEstudoHighlights(arg1) {
  return window['go']['main']['App']['ShowEstudoHighlights'](arg1);
}

export function ShowEstudoParcialHighlights(arg1) {
  return window['go']['main']['App']['ShowEstudoParcialHighlights'](arg1);
}

export function ShowHighlight(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ShowHighlight'](arg1, arg2, arg3, arg4);
}

export function ShowHoverPopup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ShowHoverPopup'](arg1, arg2, arg3, arg4, arg5);
}

export function SincronizarNuvem() {
  return window['go']['main']['App']['SincronizarNuvem']();
}

export function StartBackgroundLoop() {
  return window['go']['main']['App']['StartBackgroundLoop']();
}

export function TrocarMotor(arg1) {
  return window['go']['main']['App']['TrocarMotor'](arg1);
}

export function VerificarAtualizacao(arg1) {
  return window['go']['main']['App']['VerificarAtualizacao'](arg1);
}

export function VirarCartaBaralho(arg1, arg2) {
  return window['go']['main']['App']['VirarCartaBaralho'](arg1, arg2);
}
