// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirPastaDados() {
  return window['go']['main']['App']['AbrirPastaDados']();
}

export function AddVocab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddVocab'](arg1, arg2, arg3, arg4);
}

export function BaixarModelo(arg1) {
  return window['go']['main']['App']['BaixarModelo'](arg1);
}

export function BaixarMotor(arg1) {
  return window['go']['main']['App']['BaixarMotor'](arg1);
}

export function BaixarMotorTts(arg1) {
  return window['go']['main']['App']['BaixarMotorTts'](arg1);
}

export function BuscarPorPinyin(arg1) {
  return window['go']['main']['App']['BuscarPorPinyin'](arg1);
}

export function CaptureAndOCR() {
  return window['go']['main']['App']['CaptureAndOCR']();
}

export function CaractereCompleto(arg1) {
  return window['go']['main']['App']['CaractereCompleto'](arg1);
}

export function DecomposeCharacter(arg1) {
  return window['go']['main']['App']['DecomposeCharacter'](arg1);
}

export function ExcluirTudo() {
  return window['go']['main']['App']['ExcluirTudo']();
}

export function FalarPinyin(arg1, arg2) {
  return window['go']['main']['App']['FalarPinyin'](arg1, arg2);
}

export function GetCaptureResolution() {
  return window['go']['main']['App']['GetCaptureResolution']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCotaTraducao() {
  return window['go']['main']['App']['GetCotaTraducao']();
}

export function GetLastCards() {
  return window['go']['main']['App']['GetLastCards']();
}

export function GetMonitores() {
  return window['go']['main']['App']['GetMonitores']();
}

export function GetSessionImage(arg1) {
  return window['go']['main']['App']['GetSessionImage'](arg1);
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetSystemHardware() {
  return window['go']['main']['App']['GetSystemHardware']();
}

export function GetVocab() {
  return window['go']['main']['App']['GetVocab']();
}

export function HideHoverPopup() {
  return window['go']['main']['App']['HideHoverPopup']();
}

export function LimparArmazenamento(arg1) {
  return window['go']['main']['App']['LimparArmazenamento'](arg1);
}

export function ListarModelos() {
  return window['go']['main']['App']['ListarModelos']();
}

export function ListarMotores() {
  return window['go']['main']['App']['ListarMotores']();
}

export function ListarMotoresTts() {
  return window['go']['main']['App']['ListarMotoresTts']();
}

export function LookupWord(arg1) {
  return window['go']['main']['App']['LookupWord'](arg1);
}

export function MarcarVistoSilencioso(arg1) {
  return window['go']['main']['App']['MarcarVistoSilencioso'](arg1);
}

export function ObterTotalHanzisDicionario() {
  return window['go']['main']['App']['ObterTotalHanzisDicionario']();
}

export function RemoveVocab(arg1) {
  return window['go']['main']['App']['RemoveVocab'](arg1);
}

export function RemoverModelo(arg1) {
  return window['go']['main']['App']['RemoverModelo'](arg1);
}

export function RemoverMotor(arg1) {
  return window['go']['main']['App']['RemoverMotor'](arg1);
}

export function RemoverMotorTts(arg1) {
  return window['go']['main']['App']['RemoverMotorTts'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowEstudoHighlights(arg1) {
  return window['go']['main']['App']['ShowEstudoHighlights'](arg1);
}

export function ShowEstudoParcialHighlights(arg1) {
  return window['go']['main']['App']['ShowEstudoParcialHighlights'](arg1);
}

export function ShowHighlight(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ShowHighlight'](arg1, arg2, arg3, arg4);
}

export function ShowHoverPopup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ShowHoverPopup'](arg1, arg2, arg3, arg4, arg5);
}

export function StartBackgroundLoop() {
  return window['go']['main']['App']['StartBackgroundLoop']();
}

export function TrocarMotor(arg1) {
  return window['go']['main']['App']['TrocarMotor'](arg1);
}
